// --PLAYER
export const CHANGE_MOVEMENT_DIRECTION = 'CHANGE_MOVEMENT_DIRECTION';
export const CHANGE_ON_GROUND_STATUS = 'CHANGE_ON_GROUND_STATUS';
export const CHANGE_FALL_SPEED = 'CHANGE_FALL_SPEED';
export const UPDATE_POSITION = 'UPDATE_POSITION';
